### ISSUE TITLE
Can't scroll to start of expression in a display="block" which overflows - probable Chrome bug - but I wonder if Temml could workaround?

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#11]
I'm fairly sure this isn't a bug with Temml.

However, I thought I raise this here, because I wonder if there exists a _**suitable workaround**_ that could be implemented in Temml?

[Try to scroll to the start of the expression on Chrome](https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/10636).

This "bug" isn't seen on Firefox.

Do you recommend that I log this bug on the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list)?

If you feel here isn't a suitable place to discuss this, please feel free to close this issue.

**Comment by ronkok** [comment]
You're right that this is not a Temml bug.

If you omit `display="block"` from the `<math>` element, then you can scroll to anywhere in the expression. Maybe they think non-scrolling behavior is correct for displaystyle math.

When I submit a MathML issue to the Chromium bug tracker, the response is sometimes a literal quotation from the [MathML Core specification](https://w3c.github.io/mathml-core/). So it would not hurt to look at the spec first. If it defines `display="block"` behavior in a way that you don't like, the place to submit an issue would be [the spec's issues page](https://github.com/w3c/mathml-core/issues/new).
