### ISSUE TITLE
Demo page error (Safari 13.0.5)

### ISSUE THREAD

**Issue by nkgsv** [ronkok/Temml#12]
When I open the [demo page](https://temml.org), the following exception is raised at `temml.min.js:246`:
```
TypeError: undefined is not an object (evaluating 'e.style[t]=this.style[t]')
```
and no output is produced (more precisely I think it is raised at [`temml.js:585`](https://github.com/ronkok/Temml/blob/main/dist/temml.js#L585)). What could be the reason? My browser is Safari 13.0.5 (15608.5.11).

**Comment by ronkok** [comment]
If possible, please try upgrading to a more recent version of Safari and try again.  The page is working fine for me with Safari 16.

I do not currently have a BrowserStack subscription. Sometime in the next week, I'll spin one up. If the problem can be easily evaded, I'll do so. Either way, I'll put a notice on the site that describes which browser versions are supported.

**Comment by nkgsv** [comment]
You are right, with Safari 14.0.3 everything works fine. I haven't tried other versions, though.

**Comment by ronkok** [comment]
Thank you for the update. Since Temml runs on Safari 14, I see no need to make any changes.
