### ISSUE TITLE
`\textcolor` inside a superscript or subscript results in incorrect result

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#18]
There still remains an issue from #17 with using `\textcolor` inside a superscript or subscript.

For a better example than on #17, see [here](https://temml.org/#x%5E%7B%5Ctextcolor%7Bred%7D%7B-yz%7D%7D).

---

I really do appreciate your work on this project, I think it's still massively under used by the math community, but I suspect that will change over the next year or so as browser support for MathML gets better.

**Comment by ronkok** [comment]
A silly error on my part. Thank you for catching it so quickly. It is resolved by release v0.10.7.
