### ISSUE TITLE
Unicode ℓ SCRIPT SMALL L 0x2113 is converted to <mi class="mathcal">ℳ</mi>

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#19]
My source contains small script ℓ.

But [temml](https://temml.org/#%E2%84%93) is converting this to ℳ

```
<mi class="mathcal">ℳ</mi>
```

I don't think this was always the case (I think I would have spotted it), so suspect this is relatively new.

**Comment by ronkok** [comment]
Sorry about that. It's fixed by release 0.10.9.
