### ISSUE TITLE
Option to suppress <annotation> element from Mathml output

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#2]
For many use cases the annotation element of the mathml output is a waste of bytes and adds an unnecessary DOM element.

A key attraction of mathml is speed, optimisation and cleaner output, so I suspect this option would have wide appeal.

There is a precedent for this kind of request (from mathematica):
https://mathematica.stackexchange.com/questions/226285/how-to-exclude-annotation-encoding-mathematica-from-generated-mathml

**Comment by ronkok** [comment]
That's interesting! Without `<annotation>` and `<semantic>` elements, I could [enable](https://github.com/KaTeX/KaTeX/pull/2175), in Firefox, soft line breaks after top-level relations and binary operators, as described in **The TeXbook** page 173.

Chrome, unfortunately, will not render those soft line breaks, but even if they work only in Firefox, they would still be valuable. I'll look into it.

**Comment by ronkok** [comment]
Done in version 0.2.2. In fact, the default is now to omit the `<annotation>` element.
