### ISSUE TITLE
in subscript in `\widetilde` in MathML, `i` or `j` has no dot

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#21]
When converting TeX `\widetilde{U_i}` or `\widehat{U_i}` to MathML, `i` has no dot.

Font: Latin Modern / Asana / STIX TWO

Browser: Firefox/110.0
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1779891">Bug 1779891</a>

![image](https://user-images.githubusercontent.com/53823634/219113465-696257ad-5baa-4aed-a19a-d56f6b259cdb.png)

**Comment by ronkok** [comment]
Well, that's not good. I'll fix it, but it might take a day or two. In the meantime, you can use `\widetilde{U}_i`.

**Comment by ronkok** [comment]
On second look, there might not be much I can do about it. Temml is writing MathML with a dotted $i$, not a dot-less $\imath$. It's Firefox, not Temml, that is removing the dot. Chromium renders your example correctly.

I'll check to see if I can write a work-around, but I make no promises. I may have to write a bug report to Bugzilla, if one does not already exist.

**Comment by ronkok** [comment]
This issue is fixed by release 0.10.16.

**Comment by ronkok** [comment]
Oops, it turns out this issue still exists. I more convinced than before that there isn't much I can do about it.

**Comment by hbghlyj** [comment]
I read that
>[1069929 - Apply font features dtls](https://bugzilla.mozilla.org/show_bug.cgi?id=1069929)
dtls Dotless Forms This feature provides dotless forms for Math Alphanumeric characters, such as U+1D422 MATHEMATICAL BOLD SMALL I, U+1D423 MATHEMATICAL BOLD ...
Then I found that this Firefox-specific issue can be solved by adding the CSS rule
```
  font-feature-settings: "dtls" off;
```
![image](https://github.com/ronkok/Temml/assets/53823634/e841c7ef-fa1a-491d-be9b-a3fd9ab3b220)

**Comment by ronkok** [comment]
Good find!

I'm re-opening this issue. In the next release, I'll add that CSS rule to all the pre-written Temml CSS files.

**Comment by ronkok** [comment]
Fixed by release 0.10.24.
