### ISSUE TITLE
throwOnError

### ISSUE THREAD

**Issue by xigoi** [ronkok/Temml#22]
KaTeX has the option `throwOnError` to throw an exception when the LaTeX code is invalid instead of silently adding an error highlight to the output. Would it be possible to port this functionality to Temml?

**Comment by ronkok** [comment]
Let me think about it for a day before I respond. I am trying to make Temml installation less complicated than KaTeX and that implies certain opinionated choices.

Maybe this is important enough to overcome that principle, but I want to think about it first. What use case would be improved by a `throwOnError` option?

**Comment by xigoi** [comment]
I have a markup language compiling to HTML that includes support for compile-time rendering of math using KaTeX. I recently also added support for Temml. I'd like to know about errors as soon as possible, i.e. preferably before displaying the document. It's especially important for being able to perform static error checking (linting).

How would including `throwOnError` make the installation more complicated?

**Comment by ronkok** [comment]
Compile-time errors are a very good reason for a `throwOnError` option. I'll write it up. It will probably ship sometime later this week.

**Comment by ronkok** [comment]
Resolved via release 0.10.11.
