### ISSUE TITLE
gradient operator is italic

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#23]
When converting TeX `\nabla` to MathML, it is italic.

Browser: Firefox/113.0
![image](https://github.com/ronkok/Temml/assets/53823634/c618eb3f-2eda-4c3b-903f-0329b90b4951)

**Comment by ronkok** [comment]
Good catch. I'll fix it. A day or two may go by before I get to it.

**Comment by ronkok** [comment]
Fixed by release v0.10.12.
