### ISSUE TITLE
Add XML namespace to enable pasting into Word

### ISSUE THREAD

**Issue by mlell** [ronkok/Temml#24]
I noticed that if I copy paste the example code from temml.org into Word 2019 (Version 16.0.10394.20222) I see the raw MathML code. However, if I first paste it into a text editor and change the first line to be

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
```

I get a Word formula object. So it would be useful if the output would be in that format by default!

**Comment by ronkok** [comment]
Nice find!

The demonstration page originally did write that namespace. I removed it at the request of a user who wanted the minimum possible markup.

Now, I'll add an XML toggle switch to the demonstration page. When toggled, output will include a namespace.

**Comment by ronkok** [comment]
The toggle button is in place.
