### ISSUE TITLE
size of \rvert

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#25]
Browser: Firefox for Windows
In [Mozilla Torture Test](https://temml.org/tests/mozilla-tests.html) 14, the size of `\rvert` seems too large
Screenshot:
![image](https://github.com/ronkok/Temml/assets/53823634/e2cf111c-7235-4532-be80-97af6018fd7e)
on the left is MathML generated by Temml
LaTeX:
```
\bigg(\frac{\partial^2}
{\partial x^2} + \frac
{\partial^2}{\partial y^2}
\bigg) \big\lvert\varphi
(x+iy)\big\rvert^2
```
MathJax:
$$\bigg(\frac{\partial^2}{\partial x^2} + \frac{\partial^2}{\partial y^2}\bigg) \big\lvert\varphi(x+iy)\big\rvert^2$$
[Fred Wang&rsquo;s Mozilla MathML Test](https://fred-wang.github.io/MathFonts/mozilla_mathml_test/)
![image](https://github.com/ronkok/Temml/assets/53823634/afadcb57-3623-4172-875c-f94fbebdd464)

**Comment by ronkok** [comment]
Interesting. I'll look into it.

**Comment by ronkok** [comment]
Fixed now. Thanks for raising this issue.
