### ISSUE TITLE
LaTeX code differs from image in Mozilla test

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#26]
(This is not an issue of Temml per se)

In row 29 of https://temml.org/tests/mozilla-tests.html
`\lim_{n\rightarrow+\infty}
{\sqrt{2\pi n}\over n!}
{\binom{n}{e}}^n = 1`
![image](https://github.com/ronkok/Temml/assets/53823634/0e5fd90e-4bda-4910-a79a-db1ef4942b8e)
In the image is $\left(\frac{n}{e}\right)$ but the code provided is $\binom{n}{e}$ without the horizontal fraction line.

Also see [Fred Wang&rsquo;s Mozilla test page](https://fred-wang.github.io/MathFonts/mozilla_mathml_test/)
![image](https://github.com/ronkok/Temml/assets/53823634/19dc8e4e-452e-49e3-80d4-2aa1ab31bbec)

**Comment by ronkok** [comment]
Good catch. I'll publish a fix tomorrow, along with a couple of bug fixes.
