### ISSUE TITLE
space between last <mo> and text

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#34]
Example
```
\text{$1=$k}
```
In [LaTeX](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bamsmath%7D%0A%5Cbegin%7Bdocument%7D%0A%5C%5B%5Ctext%7B%241=%24k%7D%5C%5D%0A%5Cend%7Bdocument%7D) there is no space between `=` and `k`
![image](https://github.com/ronkok/Temml/assets/53823634/644243ac-6503-4995-8be9-ae422bd43241)
In [MathJax](https://www.mathjax.org/#demo) there is no space between `=` and `k`
![image](https://github.com/ronkok/Temml/assets/53823634/c981bdce-9557-458c-8565-b16ce17724b8)
In Temml, there is some space between `=` and `k`
![image](https://github.com/ronkok/Temml/assets/53823634/36ff13cb-9016-4150-b45b-3a20ec112b12)

**Comment by hbghlyj** [comment]
sorry, this is my error

**Comment by ronkok** [comment]
I'll look into it. It's probably fixable.

**Comment by ronkok** [comment]
Fixed by release 0.10.18.
