### ISSUE TITLE
MathML-to-TeX?

### ISSUE THREAD

**Issue by gregmax17** [ronkok/Temml#38]
This is a great tool, thank you for taking the time to build it.

My question is: is there a way to reverse the procedure and take a MathML and convert it back to TeX?

Thanks for your time and help

**Comment by ronkok** [comment]
I'm not aware of any such tool.

The Temml [copy-tex extension](https://github.com/ronkok/Temml/tree/main/contrib/copy-tex) might be a useful substitute.
