### ISSUE TITLE
Swedish letter Å (\AA) in math, italic or upright?

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#39]
in KaTeX `\AA` is italic $\largeÅ$

![image](https://github.com/ronkok/Temml/assets/53823634/a43a4705-cada-45cf-a250-6312e8dfc83c)

in [LaTeX](https://texlive.net/run?%5Cdocumentclass%5Bmargin=1cm%5D%7Bstandalone%7D%0A%5Cbegin%7Bdocument%7D%0A%24%5CAA%24%0A%5Cend%7Bdocument%7D) `$\AA$` is italic $\largeÅ$

<img src="https://github.com/ronkok/Temml/assets/53823634/b39da272-7e91-4dc5-83b9-22fe6261d434" width="300">

in Temml `\AA` is upright $\large\rmÅ$

![image](https://github.com/ronkok/Temml/assets/53823634/46859855-03d4-44ae-bb35-b0985b685744)

**Comment by ronkok** [comment]
Well, `\AA` is upright in text mode, but you are correct, LaTeX renders it as italic in math mode.

That seems odd to me. `Å` is a unit symbol, for Angstrom. I don't see why anyone would want it in italic.

Still, I'll change it as you suggest. It won't be the oddest thing we've done for LaTeX fidelity.

**Comment by ronkok** [comment]
Resolved by release v0.10.19.
