### ISSUE TITLE
Unnecessary (inferred) <mrow> DOM elements (and also uses unnecessary <mstyle> elements)

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#4]
https://github.com/KaTeX/KaTeX/issues/3333

I wrote this issue on KaTex, because was not sure Temml had the same issues, and I am not yet using Temml with my Markdown processor.

However, I forgot that I could check quickly with the demo on your homepage.

It appears Temml does also suffer from these same issues:

1. Unnecessary explicit `<mrows>` that could have been inferred.
2. Use of `<mstyle>` tags, whereas style could be applied to either mrows or other elements directly.
3. Content of the `<semantics>` tag often wrapped in an unnecessary mrow.

I'm happy to be challenged, if there is something I am not considering.

I hope I am coming across in the constructive manner that I hope I am.  I'm really motivated to help math-on-the-web becomes slick, fast, with minimal DOM elements and where authors no longer have to consider performance or their lighthouse score when writing it!

Reading the discussions and issues on the Katex repository it appears that webpage payload size and DOM size really is an issue that is affecting people writing math in the real world.

**Comment by ronkok** [comment]
In version 0.2.2, `<mstyle>` elements no longer contain a unecessary `<mrow>` child.
