### ISSUE TITLE
space before `\left(` and after `\right)`

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#42]
[LaTeX](https://texlive.net/run?%5Cdocumentclass%7Bstandalone%7D%0A%5Cbegin%7Bdocument%7D%0A%24%5Cbegin%7Barray%7D%7Bc%7D%0Aa%5Cleft(b%5Cright)c%5C%5C%0Aa(b)c%5Cend%7Barray%7D%24%0A%5Cend%7Bdocument%7D) example:
```tex
\begin{array}{c}
a\left(b\right)c
\\
a(b)c
\end{array}
```
<p align="center">
<img src=https://github.com/ronkok/Temml/assets/53823634/c9773edf-47e5-470b-b58c-d31f1d653900>
</p>

there is some extra space before `\left(` and after `\right)` (See [this post](https://tex.stackexchange.com/questions/2607/))

In Temml, the two lines are the same:
![image](https://github.com/ronkok/Temml/assets/53823634/32be03a2-b68b-40fd-9352-5cbaa073e304)

**Comment by ronkok** [comment]
I believe that Temml is emitting the correct MathML code for these parentheses. They are an `<mo>` element, with the attributes for `fence` and `form` set correctly.

You are correct in that Firefox does not rendering these parens with any extra spacing. That could be regarded as an improvement. The [post](https://tex.stackexchange.com/questions/2607/spacing-around-left-and-right) to which you linked is a discussion about how to get rid of that spacing. I tend to agree with them.

I do not intend to take any action. If you want that spacing, you'll need to take this up with the browsers.
