### ISSUE TITLE
horizontal position of superscript/subscript in `\int_\limits`

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#44]
Example
```tex
\int\limits_1^1
```
In LaTeX:
<p align="center"><img src=https://github.com/ronkok/Temml/assets/53823634/c5bb522c-d19d-4ac6-bb7b-61d73bf90350></p>

In MathJax:
$$\int\limits_1^1$$
In Temml:
![image](https://github.com/ronkok/Temml/assets/53823634/fb88cb74-0d33-468d-9378-8465fcac6e22)
the superscript/subscript seems to be misaligned with $\int$
Is this related to italic correction value of $\int$ in the font? 
<hr>
Another minor issue: in LaTeX <code>\textstyle\int_0^1 f(x)</code>
<p align="center"><img src=https://github.com/ronkok/Temml/assets/53823634/5412c85c-ec76-4841-8b0c-d317df2d6cd3></p>

In MathJax
$$\Large\textstyle\int_0^1 f(x)$$
In Temml
<p align="center"><img src=https://github.com/ronkok/Temml/assets/53823634/42f08c6b-30fe-4fd3-b242-cf34bca6c5b8 width=400></p>

the subscript 0 seems to be slightly far from $\int$

**Comment by ronkok** [comment]
The more general problem is that the browsers do a poor job at italic correction in general. Sometimes they ignore italic correction altogether. What's worse is that each browser has a _different_ italic correction problem than the others.

That's makes any workaround very difficult. A workaround would have to be customized for:
* each browser
* each font
* each glyph's italic correction metrics.

That's more than I signed up to do. I recognize the problem, but I do not intend to take any action.
