### ISSUE TITLE
spacing between `\mathrm{a}a`

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#46]
This is an issue of Firefox. It works well in Chrome.
Example:
```tex
\begin{array}{c}
\mathrm{aa}a\mathrm{aa}
\\
\mathrm{a}\mathrm{a}a\mathrm{a}\mathrm{a}
\end{array}
```
In [LaTeX](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bamsmath%7D%0A%5Cbegin%7Bdocument%7D%0A%24%5Cbegin%7Barray%7D%7Bc%7D%0A%5Cmathrm%7Baa%7Da%5Cmathrm%7Baa%7D%0A%5C%5C%0A%5Cmathrm%7Ba%7D%5Cmathrm%7Ba%7Da%5Cmathrm%7Ba%7D%5Cmathrm%7Ba%7D%0A%5Cend%7Barray%7D%24%0A%5Cend%7Bdocument%7D): Two lines have same spacing
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/016b216a-71fd-4d99-a2ad-80323c92494d"></p>
In Temml (Firefox): Two lines have different spacing
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/fe7f6a25-1a07-4bce-9fe9-3b53677cadcc" width="400"></p>
In Temml (Chrome): Two lines have same spacing
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/22565c96-d1f3-4ba0-bc63-4be21d9c84f0" width="400"></p>

**Comment by ronkok** [comment]
For this example, Temml is emitting MathML that is fine. Firefox has no reason to insert extra spacing. So this is not a Temml bug.

Having said that, I see that Temml's MathML is a little more verbose than it needs to be in this example. It is writing some unnecessary `<mrow>` nodes. I will take a look at that, but I make no promise as to when or if I will make a change. This would be an optional Temml improvement, not a required one.

**Comment by ronkok** [comment]
After review, I have decided to take no action on this issue.

Here's the situation: Firefox is adding extra space around some `<mi>` elements. They seem to crop up on or about `\mathrm{…}`.  You may be aware that a `<mi>` element that contains a single letter is normally rendered as italic in MathML. To get upright rendering for `\mathrm{…}`, I use `<mi mathvariant="normal">`. But Firefox erroneously adds space around that element. So I wrap it with a `<mrow>` to suppress the spacing.

This issue has now revealed that Firefox adds space around an `<mi>` adjacent to the `mathvariant="normal"` element. Wrapping with a `<mrow>` does not help.

I really don't think there is much that I can do. This is a Firefox problem and they will have to fix it.
