### ISSUE TITLE
`\color{}` in array environment

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#47]
Example
```tex
\begin{array}{l}
\color{red}a
\\
b
\\
c
\end{array}
```
[LaTeX](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bxcolor%7D%0A%5Cusepackage%7Bamsmath%7D%0A%5Cbegin%7Bdocument%7D%0A%24%5Cbegin%7Barray%7D%7Bl%7D%0A%5Ccolor%7Bred%7Da%0A%5C%5C%0Ab%0A%5C%5C%0Ac%0A%5Cend%7Barray%7D%24%0A%5Cend%7Bdocument%7D)
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/8ea53eca-d1a5-4956-ad81-4296498f4057"></p>
KaTeX
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/e3d344aa-327a-4f3d-b81f-404b9edca8cc" height="100"></p>
Temml (Browser: Chrome)
<p align="center"><img width="607" src="https://github.com/ronkok/Temml/assets/53823634/ad80f474-e511-43c6-abc1-27631830156b"></p>

**Comment by ronkok** [comment]
Oh dear, that's a serious problem. I'll go to work and I'll have a fix out later this week.

**Comment by ronkok** [comment]
Fixed via release v0.10.21.

@hbghlyj Thank you for raising this issue.
