### ISSUE TITLE
\over in \Set

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#50]
Example
```tex
\Set{a\over a}
\hskip1cm
{a\over a}
```
in [LaTeX](https://texlive.net/run?%5Cdocumentclass%5Bmargin=1mm%5D%7Bstandalone%7D%0A%5Cusepackage%7Bbraket%7D%0A%5Cbegin%7Bdocument%7D%0A%5C(%5CSet%7Ba%5Cover%20a%7D%5Chskip1cm%7Ba%5Cover%20a%7D%5C)%0A%5Cend%7Bdocument%7D)
<p align="center"><img src="https://github.com/ronkok/Temml/assets/53823634/6bad9655-b658-44c9-96d1-3e4405cfc515" width="150"></p>

in [Temml](https://temml.org/#%5CSet%7Ba%5Cover%20a%7D%0A%5Chskip1cm%0A%7Ba%5Cover%20a%7D)  the numerator is not centered, as there is a &lt;mspace> in front of it
```xml
<mrow><mspace width="0.2222em"></mspace><mi>a</mi></mrow>
```
![image](https://github.com/ronkok/Temml/assets/53823634/468a3e8b-16bf-45b1-8010-1425eea380de)

**Comment by ronkok** [comment]
Fixed by release v0.10.22.
