### ISSUE TITLE
add a sans-serif font

### ISSUE THREAD

**Issue by berrymot** [ronkok/Temml#52]
which is available in the gh-pages branch of notofonts/math

beware: there is a discussion there about splitting it into separate Sans and Serif; if that split occurs (a) i will let you know (b) probably change it to the serif one

lol my primary motivations for this are stresstesting that font and seeing if it looks decent on [this mess of a dictionary](https://github.com/berrymot/xlasisku)

:3

**Comment by ronkok** [comment]
Interesting.  Thank you for the pointer to notofonts/math. The last info I had was this [discussion](https://github.com/notofonts/math/issues/14), which is now 10 months old.

I will probably wait before featuring this font in Temml docs. Hopefully, they'll work out their serif/sans-serif inconsistency.

At one point, there was talk of Android using this font as their system math font. Do you know if that has shipped yet?

**Comment by berrymot** [comment]
it hasn't as of when i switched from mathjax to temml for the project i linked ^, which was ... september iirc

**Comment by berrymot** [comment]
in the meantime hmmm maybe fira math would be cool?

**Comment by ronkok** [comment]
Fira Math does look interesting, but I don't see a web font in the repository, just an `otf` font. If and when there exists a `woff2` font, I will look into it more thoroughly.

**Comment by ronkok** [comment]
I see now that Fira Math is available at Fred Wang's [font page](https://fred-wang.github.io/MathFonts/). I'll look into it.

**Comment by ronkok** [comment]
I've added Fira Math as an optional CSS file. So I take this issue as resolved.
