### ISSUE TITLE
HTML <label> in Temml home page

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#55]
In the HTML source for Temml home page, at line 51,
```html
<label for="demoRendering">Output:</label>
<br/>
  
<div class="ioArea" id="demoRendering">
```
The value of the `for` attribute of the &lt;label> element refers to a &lt;div> element, but:

Cite MDN [&lt;label>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

> Elements that can be associated with a &lt;label> element include [&lt;button>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), [&lt;input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) (except for type="hidden"), [&lt;meter>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter), [&lt;output>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output), [&lt;progress>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress), [&lt;select>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) and [&lt;textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea).

Also, the &lt;main> tag on line 20 is not closed:
![image](https://github.com/ronkok/Temml/assets/53823634/7f83c509-de53-4094-bdae-6adf2092fd00)
I suggest adding &lt;/main> before &lt;/body> on line 233.

**Comment by ronkok** [comment]
Thank you for alerting me to these issues. Fixed now.
