### ISSUE TITLE
TypeScript error TS1183 in temml.d.ts

### ISSUE THREAD

**Issue by againey** [ronkok/Temml#56]
When converting my JS server to TS, I ran into the following error on [line 44 of `dist/temml.d.ts`](https://github.com/ronkok/Temml/blob/138b63cde5dc41c747b44bc7626e3d406abe5bdf/dist/temml.d.ts#L44):

> error TS1183: An implementation cannot be declared in ambient contexts.

Removing the curly brackets or replacing them with a semicolon appears to fix the problem. That makes sense to me, but my knowledge of TypeScript is very limited, thus I have no idea if there's more or different that should be done to address the problem.

**Comment by ronkok** [comment]
My knowledge of TypeScript is also paper thin. But I think you correct. That pair of braces should not be there. I've removed them in release v0.10.22.
