### ISSUE TITLE
Jekyll must be disabled for Github Pages, else KaTeX test on line 840 fails

### ISSUE THREAD

**Issue by berrymot** [ronkok/Temml#57]
Jekyll's error message:
```
Rendering Liquid: temml/test/katex-tests.md github-pages 228 | Error: Liquid syntax error (line 840): Variable '{{\tiny a+b}' was not properly terminated with regexp: /\}\}/```

**Comment by ronkok** [comment]
The tables in https://github.com/ronkok/Temml/blob/main/test/katex-tests.md are written in the reStructuredText grid table format. If Jekyll is written to read Markdown pipe tables, then it is not surprising to see a problem.

**Comment by berrymot** [comment]
ahh got it
