### ISSUE TITLE
\mathrm{d} missing space?

### ISSUE THREAD

**Issue by MedievalSteel** [ronkok/Temml#62]
\mathrm and \text missing space?
![Screenshot 2024-04-13 212122](https://github.com/ronkok/Temml/assets/74715689/b5a6dc1e-984e-4bf2-bc39-b66b7b3571ff)
![Screenshot 2024-04-13 212111](https://github.com/ronkok/Temml/assets/74715689/183ca7ad-c74c-487b-a691-95d11b48953b)

**Comment by ronkok** [comment]
Yup, that needs work. It would be nice if the browsers got this right without my help. WebKit (Safari) actually does get this one right. But Chromium and Firefox get it wrong, so I'll do a workaround.

Temml already has a test for `needsLeadingSpace` before an `<mo>` element. I need to do a better job defining when `needsLeadingSpace` should be true.

I''l work on it, but a few days may go by before I get to it.

**Comment by ronkok** [comment]
Fixed by release v0.10.26.
