### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by traeblain** [ronkok/Temml#63]
Quick reminder to publish the latest version to NPM.

I've never used it, but told this is the best tool to auto publish so you don't have to worry about and will work when you release a new version.

https://github.com/danitseitlin/package-deployer

**Comment by ronkok** [comment]
I just type `npm publish`. That usually works fine. On the latest release, I got an error message, saying that I did not have rights to overwrite the previous release. Checking now, I see that I had not updated the version number in the `package.json` file. Perhaps I should look into your idea to automate the release procedure. Or perhaps I should just do each release in the morning when I am fresh and not late in the day when I am tired and less apt to follow up.

I plan to issue another release in a couple of days. In the future, I'll follow through on any NPM publishing issues until I have them resolved.

**Comment by ronkok** [comment]
Release v0.10.26 is now out. The npm publish worked correctly this time. I think we're back on track.
