### ISSUE TITLE
Double backslashes (`\\`) (forced line break) works in inline mode but not display mode

### ISSUE THREAD

**Issue by calebeby** [ronkok/Temml#68]
https://temml.org/#a%20%5C%5C%20b

When in display mode, the elements are shown on one line. When in inline mode, they are split into two lines (correctly).

KateX splits it correctly in both cases:

https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22a%20%5C%5C%5C%5C%20b%22%7D

**Comment by ronkok** [comment]
Disagree. LaTeX does not split the expression `a \\ b` into two lines when in display mode.

Ref: https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bamsmath%7D%0A%5Cbegin%7Bdocument%7D%0A%5C%5Ba%20%5C%5C%20b%5C%5D%0A%0A%5C(a%20%5C%5C%20b%5C)%0A%5Cend%7Bdocument%7D

**Comment by calebeby** [comment]
Oh huh, didn't realize that. How would you force it to split a line in display mode?

**Comment by ronkok** [comment]
You can always use a LaTeX [environment](https://temml.org/docs/en/supported#environments).
