### ISSUE TITLE
\vdots or unicode ⋮ produces `<mi>` as child of `<mi>`

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#7]
Hi, thank you for all your effort in creating this library - in general I find the output spot on - you have clearly gone to a lot of effort to ensure the output is top quality.

I've found one very small issue when using `\vdots` or unicode `⋮`

Input:

```
\begin{array}{c}
a\\
\vdots\\
z
\end{array}
```

Output:
```
<math display="block">
  <mtable rowspacing="0.16em" columnalign="center" columnspacing="1em">
    <mtr>
      <mtd>
        <mi>a</mi>
      </mtd>
    </mtr>
    <mtr>
      <mtd>
        <mi>
          <mi>⋮</mi>
          <mspace width="0pt" height="14.944pt"></mspace>
        </mi>
      </mtd>
    </mtr>
    <mtr>
      <mtd>
        <mi>z</mi>
      </mtd>
    </mtr>
  </mtable>
</math>
```

The result of this is that we get a nested `mi` inside a `mi`.

I always take the output of validators with a pinch of salt, but for what it's worth [validator.w3.org/nu](https://validator.w3.org/nu/#textarea) reports `Element mi not allowed as child of element mi in this context` and ` Element mspace not allowed as child of element mi in this context`.

With nested mi (and mspace):
![image](https://user-images.githubusercontent.com/750365/173351663-8d022b92-0ead-42ee-bfc5-cfabc72b8062.png)

Without nested mi (and keeping the mspace):
![image](https://user-images.githubusercontent.com/750365/173351727-d4f90401-c89c-4714-adb8-17815f3b3edb.png)

Without nested mi (and removing the mspace):
![image](https://user-images.githubusercontent.com/750365/173352425-74b11076-2395-4d86-87c5-1b995a2fffaa.png)

**Comment by ronkok** [comment]
@universemaster Thank you for raising this issue. It is a legitimate concern, and I will look into it. On the other hand, I do not think it is urgent and I'm a little busy right now. A week or two may go by before I address it.
