### ISSUE TITLE
`\color` and right delimiter

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#73]
I noticed a difference between KaTeX and Temml in the code:
```tex
\left(\color{red}\right)abc
```
In KaTeX, the right delimiter is colored red, but in [Temml](https://temml.org/#%5Cleft(%5Ccolor%7Bred%7D%5Cright)abc), the right delimiter is not colored red.
![image](https://github.com/user-attachments/assets/ebb135cb-a5a3-44de-9ab3-cf2d989d7f3f)

Is this a bug or a feature?

**Comment by ronkok** [comment]
It' a bug. I'll look into it.

**Comment by ronkok** [comment]
Fixed in release v0.10.30.
