### ISSUE TITLE
Vertical alignment in a \left \right fence is different in Chromium when Temml wraps in an mrow

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#8]
Thanks for your work in updating the library to work in Chromium.

I've spotted an issue whose root cause may or may not be Temml.

In Chrome Canary using \left \right for fences creates different vertical alignment of the contents compared to not using \left \right.

See this [demo](https://temml.org/#(uv)%5C%5C%0A%5Cleft(uv%5Cright)%0A%0A(x)%0A%5Cleft(x%5Cright)%0A%0A(st)%0A%5Cleft(st%5Cright)%0A%0A%7Cx%7C%0A%5Cleft%7Cx%5Cright%7C%0A%0A%7Ct%7C%0A%5Cleft%7C%20t%20%5Cright%7C).

Notice that tall characters like `t` look OK, but shorter characters don't.

If I manually remove the wrapping mrow that Temml puts in for line-breaking, the result is as expected (expect for | ).  See this live DOM viewer [demo](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cmath%20display%3D%22block%22%3E%0A%20%20%3Cmrow%3E%0A%20%20%20%20%3Cmo%20form%3D%22prefix%22%20stretchy%3D%22false%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%3Cmi%3Eu%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3Ev%3C%2Fmi%3E%0A%20%20%20%20%3Cmo%20form%3D%22postfix%22%20stretchy%3D%22false%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%3Cmo%3E%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22prefix%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmi%3Eu%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmi%3Ev%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22postfix%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%3Cmo%20form%3D%22prefix%22%20stretchy%3D%22false%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%3Cmi%3Ex%3C%2Fmi%3E%0A%20%20%20%20%3Cmo%20form%3D%22postfix%22%20stretchy%3D%22false%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22prefix%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmi%3Ex%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22postfix%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%3Cmo%20form%3D%22prefix%22%20stretchy%3D%22false%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%3Cmi%3Es%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3Et%3C%2Fmi%3E%0A%20%20%20%20%3Cmo%20form%3D%22postfix%22%20stretchy%3D%22false%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22prefix%22%3E(%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmi%3Es%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmi%3Et%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22postfix%22%3E)%3C%2Fmo%3E%0A%20%20%20%20%3Cmi%3E%7C%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3Ex%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3E%7C%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22prefix%22%3E%7C%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmi%3Ex%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22postfix%22%3E%7C%3C%2Fmo%3E%0A%20%20%20%20%3Cmi%3E%7C%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3Et%3C%2Fmi%3E%0A%20%20%20%20%3Cmi%3E%7C%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22prefix%22%3E%7C%3C%2Fmo%3E%0A%20%20%20%20%20%20%3Cmi%3Et%3C%2Fmi%3E%0A%20%20%20%20%20%20%3Cmo%20fence%3D%22true%22%20form%3D%22postfix%22%3E%7C%3C%2Fmo%3E%0A%20%20%3C%2Fmrow%3E%0A%3C%2Fmath%3E%0A).

I'm not sure whether the root cause is:
- The mrow layout algorithm in the [Mathml core spec](https://w3c.github.io/mathml-core/#algorithm-for-stretching-operators-along-the-block-axis).
- The current chromium implementation.
- Or a problem with Temml itself.

I've tried unsuccessfully to add an option to not perform the mrow line-breaking in Temml.  Such an option would (partially) work around the problem for authors who do not need the mrow line-breaking features.

Here's a screenshot of the current situation from the with Temml website at version 0.7.1:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/750365/183477769-100b39f0-63bb-4c67-92f4-fbf3d3eb029d.png">

<details> 
  <summary>
This was produced with this input:</summary>

```

(uv)\\
\left(uv\right)

(x)
\left(x\right)

(st)
\left(st\right)

|x|
\left|x\right|

|t|
\left| t \right|

```

</details>

<details> 
  <summary>
Which produces this Mathml (with Temml version 0.7.1):</summary>

```
<math display="block">
  <mrow>
    <mo form="prefix" stretchy="false">(</mo>
    <mi>u</mi>
    <mi>v</mi>
    <mo form="postfix" stretchy="false">)</mo>
    <mo></mo>
    <mrow>
      <mo fence="true" form="prefix">(</mo>
      <mi>u</mi>
      <mi>v</mi>
      <mo fence="true" form="postfix">)</mo>
    </mrow>
    <mo form="prefix" stretchy="false">(</mo>
    <mi>x</mi>
    <mo form="postfix" stretchy="false">)</mo>
    <mrow>
      <mo fence="true" form="prefix">(</mo>
      <mi>x</mi>
      <mo fence="true" form="postfix">)</mo>
    </mrow>
    <mo form="prefix" stretchy="false">(</mo>
    <mi>s</mi>
    <mi>t</mi>
    <mo form="postfix" stretchy="false">)</mo>
    <mrow>
      <mo fence="true" form="prefix">(</mo>
      <mi>s</mi>
      <mi>t</mi>
      <mo fence="true" form="postfix">)</mo>
    </mrow>
    <mi>|</mi>
    <mi>x</mi>
    <mi>|</mi>
    <mrow>
      <mo fence="true" form="prefix">|</mo>
      <mi>x</mi>
      <mo fence="true" form="postfix">|</mo>
    </mrow>
    <mi>|</mi>
    <mi>t</mi>
    <mi>|</mi>
    <mrow>
      <mo fence="true" form="prefix">|</mo>
      <mi>t</mi>
      <mo fence="true" form="postfix">|</mo>
    </mrow>
  </mrow>
</math>
```

</details>

**Comment by ronkok** [comment]
An `<mrow>` should not change the rendering of nested parentheses. I take this to be a Chromium problem. They have other delimiter problems, as well. I wrote [an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1350830&q=MathML&can=2) in their bug tracker yesterday.

**Comment by ronkok** [comment]
As an aside, I am considering removing soft line-breaks from Temml, since Chromium will not render the soft line breaks.

@universemaster Any comments?

**Comment by universemaster** [comment]
Personally, I do not have a use for the soft line breaks in any browser.  Thus, I would prefer fewer elements to be output by Temml for parsing/download efficiency.  So, in conclusion, I support removing soft line breaks from Temml.

**Comment by ronkok** [comment]
Closing this issue, since it is a Chromium problem.
