### ISSUE TITLE
Using `ö` in `\text{ ... }` produces repeated text  (Rare issue - with workaround)

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#9]
Here is a [demo](https://temml.org/#g%5E%7B-1%7D%20f%20%5Ctext%7B%20is%20also%20a%20M%C3%B6bius%20map.%7D).

I understand that the documentation advises that I can use `g^{-1} f \text{ is also a M\"{o}bius map.}` so I have done that instead.  I suspect that this issue very rarely occurs in the wild.

**Comment by ronkok** [comment]
Well, that's not good. I'll look into it. Thank you for reporting this.

**Comment by ronkok** [comment]
Fixed by version 0.7.2
